data_path: abstracts.csv
output_base_dir: outputs_by_cluster
embedding_model: paraphrase-multilingual-MiniLM-L12-v2
min_cluster_size: 10
n_components: 5
n_neighbors: 15
random_state: 42
min_docs_for_cluster: 10
